// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvxyzobrvhaggfhbngae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2eHl6b2JydmhhZ2dmaGJuZ2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzc4MTgsImV4cCI6MjA2Njk1MzgxOH0.iI9ktmX6vSWs6v5lGIRCQTgXvk7s_aPecWmdaAgayP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});